jwt:
  secret-key: ecf1222c-88fd-47f3-988f-bdd78bade1ad
  expiration-at: 900000
  expiration-rt: 1800000
  user: admin
  password: Admin_1234

logging:
  level:
    com:
      example: DEBUG
    root: INFO
    web: DEBUG

server:
  port: 9000

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/login
    redis:
      host: redis-10893.c274.us-east-1-3.ec2.cloud.redislabs.com
      #database: 2
      port: 10893
      password: f04MdnPj80wFbvMEVsikmfzE8gUUEtfn

  webflux:
    base-path: /api



