jwt:
  secretKey: ecf1222c-88fd-47f3-988f-bdd78bade1ad

logging:
  level:
    com:
      example: DEBUG
    root: INFO
    web: DEBUG

server:
  port: 9000

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/login
  webflux:
    base-path: /api



